### ISSUE TITLE
Failing to build waf-1.8.17

### ISSUE THREAD

**Issue by matheusfillipe** [mxe/mxe#2485]
I am following the tutorial: https://mxe.cc/#tutorial and its failing to run make to build with that error:

```
[build]       aubio                   i686-w64-mingw32.static

Failed to build package aubio for target i686-w64-mingw32.static!
------------------------------------------------------------
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Node.py", line 361, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
make[1]: *** [Makefile:846: build-only-aubio_i686-w64-mingw32.static] Error 2
make[1]: Leaving directory '/home/matheus/mxe'
real    0m2.513s
user    0m2.435s
sys     0m0.103s
------------------------------------------------------------
[log]      /home/matheus/mxe/log/aubio_i686-w64-mingw32.static

make: *** [Makefile:834: /home/matheus/mxe/usr/i686-w64-mingw32.static/installed/aubio] Error 1

```
If i go to: /mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17 and run python (it's python 3.8.2) I get:

```
------> Executing code from the top-level wscript <-----
Traceback (most recent call last):
  File "/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/waflib/Node.py", line 540, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/waflib/Scripting.py", line 161, in waf_entry_point
    run_commands()
  File "/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/waflib/Scripting.py", line 263, in run_commands
    ctx = run_command(cmd_name)
  File "/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/waflib/Scripting.py", line 247, in run_command
    ctx.execute()
  File "/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/waflib/Scripting.py", line 623, in execute
    return execute_method(self)
  File "/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/waflib/Build.py", line 248, in execute
    self.load_envs()
  File "/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/waflib/Build.py", line 209, in load_envs
    lst = node.ant_glob('**/*%s' % CACHE_SUFFIX, quiet=True)
  File "/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/waflib/Node.py", line 631, in ant_glob
    ret = [x for x in self.ant_iter(accept=accept, pats=[to_pat(incl), to_pat(excl)], maxdepth=kw.get('maxdepth', 25), dir=dir, src=src, remove=kw.get('remove', True))]
  File "/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/waflib/Node.py", line 631, in <listcomp>
    ret = [x for x in self.ant_iter(accept=accept, pats=[to_pat(incl), to_pat(excl)], maxdepth=kw.get('maxdepth', 25), dir=dir, src=src, remove=kw.get('remove', True))]
RuntimeError: generator raised StopIteration

```

but works with python2:
```
------> Executing code from the top-level wscript <-----
Waf: Entering directory `/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/build'
[1/1] Creating waf
-> preparing 'tmp-waf-1.8.17'
   adding waflib/Runner.py as waflib/Runner.py
   adding waflib/Errors.py as waflib/Errors.py
   adding waflib/__init__.py as waflib/__init__.py
   adding waflib/ConfigSet.py as waflib/ConfigSet.py
   adding waflib/Task.py as waflib/Task.py
   adding waflib/Options.py as waflib/Options.py
   adding waflib/Configure.py as waflib/Configure.py
   adding waflib/Context.py as waflib/Context.py
   adding waflib/fixpy2.py as waflib/fixpy2.py
   adding waflib/Utils.py as waflib/Utils.py
   adding waflib/ansiterm.py as waflib/ansiterm.py
   adding waflib/Build.py as waflib/Build.py
   adding waflib/TaskGen.py as waflib/TaskGen.py
   adding waflib/Node.py as waflib/Node.py
   adding waflib/Scripting.py as waflib/Scripting.py
   adding waflib/Logs.py as waflib/Logs.py
   adding waflib/Tools/gas.py as waflib/Tools/gas.py
   adding waflib/Tools/d_scan.py as waflib/Tools/d_scan.py
   adding waflib/Tools/c_preproc.py as waflib/Tools/c_preproc.py
   adding waflib/Tools/xlcxx.py as waflib/Tools/xlcxx.py
   adding waflib/Tools/c_tests.py as waflib/Tools/c_tests.py
   adding waflib/Tools/glib2.py as waflib/Tools/glib2.py
   adding waflib/Tools/icpc.py as waflib/Tools/icpc.py
   adding waflib/Tools/bison.py as waflib/Tools/bison.py
   adding waflib/Tools/clangxx.py as waflib/Tools/clangxx.py
   adding waflib/Tools/__init__.py as waflib/Tools/__init__.py
   adding waflib/Tools/ldc2.py as waflib/Tools/ldc2.py
   adding waflib/Tools/compiler_fc.py as waflib/Tools/compiler_fc.py
   adding waflib/Tools/ruby.py as waflib/Tools/ruby.py
   adding waflib/Tools/c_osx.py as waflib/Tools/c_osx.py
   adding waflib/Tools/flex.py as waflib/Tools/flex.py
   adding waflib/Tools/fc.py as waflib/Tools/fc.py
   adding waflib/Tools/ifort.py as waflib/Tools/ifort.py
   adding waflib/Tools/clang.py as waflib/Tools/clang.py
   adding waflib/Tools/g95.py as waflib/Tools/g95.py
   adding waflib/Tools/ar.py as waflib/Tools/ar.py
   adding waflib/Tools/intltool.py as waflib/Tools/intltool.py
   adding waflib/Tools/errcheck.py as waflib/Tools/errcheck.py
   adding waflib/Tools/lua.py as waflib/Tools/lua.py
   adding waflib/Tools/msvc.py as waflib/Tools/msvc.py
   adding waflib/Tools/perl.py as waflib/Tools/perl.py
   adding waflib/Tools/icc.py as waflib/Tools/icc.py
   adding waflib/Tools/compiler_c.py as waflib/Tools/compiler_c.py
   adding waflib/Tools/fc_config.py as waflib/Tools/fc_config.py
   adding waflib/Tools/cs.py as waflib/Tools/cs.py
   adding waflib/Tools/suncc.py as waflib/Tools/suncc.py
   adding waflib/Tools/gcc.py as waflib/Tools/gcc.py
   adding waflib/Tools/irixcc.py as waflib/Tools/irixcc.py
   adding waflib/Tools/c_aliases.py as waflib/Tools/c_aliases.py
   adding waflib/Tools/d.py as waflib/Tools/d.py
   adding waflib/Tools/cxx.py as waflib/Tools/cxx.py
   adding waflib/Tools/compiler_d.py as waflib/Tools/compiler_d.py
   adding waflib/Tools/kde4.py as waflib/Tools/kde4.py
   adding waflib/Tools/suncxx.py as waflib/Tools/suncxx.py
   adding waflib/Tools/nasm.py as waflib/Tools/nasm.py
   adding waflib/Tools/tex.py as waflib/Tools/tex.py
   adding waflib/Tools/xlc.py as waflib/Tools/xlc.py
   adding waflib/Tools/fc_scan.py as waflib/Tools/fc_scan.py
   adding waflib/Tools/gxx.py as waflib/Tools/gxx.py
   adding waflib/Tools/qt5.py as waflib/Tools/qt5.py
   adding waflib/Tools/asm.py as waflib/Tools/asm.py
   adding waflib/Tools/compiler_cxx.py as waflib/Tools/compiler_cxx.py
   adding waflib/Tools/dbus.py as waflib/Tools/dbus.py
   adding waflib/Tools/ccroot.py as waflib/Tools/ccroot.py
   adding waflib/Tools/gfortran.py as waflib/Tools/gfortran.py
   adding waflib/Tools/vala.py as waflib/Tools/vala.py
   adding waflib/Tools/c_config.py as waflib/Tools/c_config.py
   adding waflib/Tools/python.py as waflib/Tools/python.py
   adding waflib/Tools/gdc.py as waflib/Tools/gdc.py
   adding waflib/Tools/javaw.py as waflib/Tools/javaw.py
   adding waflib/Tools/gnu_dirs.py as waflib/Tools/gnu_dirs.py
   adding waflib/Tools/winres.py as waflib/Tools/winres.py
   adding waflib/Tools/c.py as waflib/Tools/c.py
   adding waflib/Tools/dmd.py as waflib/Tools/dmd.py
   adding waflib/Tools/qt4.py as waflib/Tools/qt4.py
   adding waflib/Tools/d_config.py as waflib/Tools/d_config.py
   adding waflib/Tools/waf_unit_test.py as waflib/Tools/waf_unit_test.py
   adding waflib/extras/__init__.py as waflib/extras/__init__.py
   adding waflib/extras/compat15.py as waflib/extras/compat15.py
Waf: Leaving directory `/home/matheus/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/build'
'build' finished successfully (0.393s)

```
But if i run make again i get the error of course. I've seen the main makefile should be using python 2, I will add the path manually and make a test from the start again to see if thats the issue.

**SYSTEM INFO**

```
OS: Arch Linux x86_64                                                                                         
Host: Inspiron 15 7000 Gaming                                                                                 
Kernel: 5.4.31-1-lts                                                                                          
Packages: 1904 (pacman), 44 (flatpak)                                                                         
Shell: zsh 5.8                                                                                                
Resolution: 1920x1080                                                                                         
DE: KDE5                                                                                                      
WM: KWin                                                                                                      
WM Theme: McMojave                                                                                            
Theme: McMojave [KDE5], Breeze-Dark [GTK2/3]                                                                  
Icons: breeze-dark [KDE5], breeze-dark [GTK2/3]                                                               
Terminal: /dev/pts/4 
CPU: Intel i7-7700HQ (8) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
GPU: Intel HD Graphics 630 
Memory: 8744MiB / 15880MiB 
```

**Comment by tonytheodore** [comment]
Fixed in https://github.com/mxe/mxe/commit/dcc6131619a37d8e4c2e9ba6cea700c61a9c71d6
