### ISSUE TITLE
Could not find section for RVA happened when trying to find the DLL dependency

### ISSUE THREAD

**Issue by wentongwu** [mxe/mxe#2617]
I'm using copydlldeps.py to find the DLL dependency, but got the error 
```
Traceback (most recent call last):
  File "copydlldeps.py", line 155, in <module>
    for dependency_dll in get_imports(pe_filename_full):
  File "copydlldeps.py", line 84, in get_imports
    seek_to_rva(rva)
  File "copydlldeps.py", line 69, in seek_to_rva
    raise ValueError('Could not find section for RVA.')
ValueError: Could not find section for RVA.
```
whether using the exe file built by myself or dll file built by the source.
anyone has the same problem? Appreciate any help, thanks a lot!

**Comment by sebastienraillet** [comment]
Hi @wentongwu,
I'm facing the same issue. Did you finally find a solution ?
Thanks 😃
