### ISSUE TITLE
Failed to build package aubio for target i686-w64-mingw32.static

### ISSUE THREAD

**Issue by agonzalv** [mxe/mxe#2696]
Hi everyone, 
I tried to install MXE over my fedora laptop. I followed official instructions for fedora [here](https://mxe.cc/#tutorial), but I received the following message after the 3a step with the command `make`. 
```
Failed to build package aubio for target i686-w64-mingw32.static!
------------------------------------------------------------
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Node.py", line 361, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
make[1]: *** [Makefile:874: build-only-aubio_i686-w64-mingw32.static] Error 2
make[1]: Leaving directory '/home/mxe'
real	0m2.444s
user	0m2.322s
sys	0m0.157s
------------------------------------------------------------
[log]      /home/mxe/log/aubio_i686-w64-mingw32.static

make: *** [Makefile:862: /home/mxe/usr/i686-w64-mingw32.static/installed/aubio] Error 1
``̀
I am not an expert in compilation, but does anyone have an idea what I could do to continue the setup process ?

**Comment by pon-droid** [comment]
Same thing is happening to me, I am also using fedora.

**Comment by MarcoBorrini99** [comment]
Archlinux here... same error

**Comment by luspi** [comment]
This is still an issue (ArchLinux). The only way to get past it (afaict) is to skip building aubio (rename the abuio* files in src/).

**Comment by phoenixqm** [comment]
Same thing is happening to me, I am using Debian 11

**Comment by CropWatchDevelopment** [comment]
Still having this issue, any fix yet? Linux Mint (ubuntu 20.04

**Comment by mabrand** [comment]
You will probably find a clue in log/aubio_i686-w64-mingw32.static. Please post this file.

**Comment by prime6809** [comment]
Having same problem here, Ubuntu 22.04 LTS,

log file : 

make[1]: Entering directory '/opt/mxe'
uname -a
Linux htpc 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
git log --pretty=tformat:"%H - %s [%ar] [%d]" -1
114b1ac37013122fdb77017eca324c315a93dd93 - add pkgconfig files to HDF4 [5 days ago] [ (HEAD -> master, origin/master, origin/HEAD)]
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
autoconf --version 2>/dev/null | head -1
autoconf (GNU Autoconf) 2.71
automake --version 2>/dev/null | head -1
automake (GNU automake) 1.16.5
gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

python --version
Python 3.10.6
perl --version 2>&1 | head -3

This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-gnu-thread-multi
(with 57 registered patches, see perl -V for more detail)
rm -rf   '/opt/mxe/tmp-aubio-i686-w64-mingw32.static'
mkdir -p '/opt/mxe/tmp-aubio-i686-w64-mingw32.static'
mkdir -p '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2'
mkdir -p '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_'
# disable wine with readonly directory
# see https://github.com/mxe/mxe/issues/841
mkdir -p '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/readonly'
chmod 0555 '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/readonly'
cd '/opt/mxe/tmp-aubio-i686-w64-mingw32.static' &&      tar xjf '/opt/mxe/pkg/aubio-0.4.2.tar.bz2'
cd '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2'
(cd '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2' && patch -p1 -u) < /opt/mxe/src/aubio-1-fixes.patch
patching file wscript
patching file wscript
patching file wscript
patching file src/wscript_build
patching file src/wscript_build
patching file wscript
patching file aubio.pc.in
patching file wscript
patching file wscript
patching file src/io/source_avcodec.c
cd '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_' &&      tar xjf '/opt/mxe/pkg/waf-1.8.17.tar.bz2'
cd '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17'
rm -rf '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2/waf' '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2/waflib'
cd '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2' && AR='i686-w64-mingw32.static-ar' CC='i686-w64-mingw32.static-gcc' PKGCONFIG='i686-w64-mingw32.static-pkg-config'  '/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/waf' configure -j '4' --with-target-platform='win32' --prefix='/opt/mxe/usr/i686-w64-mingw32.static' --enable-fftw3f --libdir='/opt/mxe/usr/i686-w64-mingw32.static/lib'  --enable-static --disable-shared --disable-jack
Traceback (most recent call last):
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Node.py", line 312, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Scripting.py", line 110, in waf_entry_point
    run_commands()
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Scripting.py", line 167, in run_commands
    parse_options()
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Scripting.py", line 140, in parse_options
    Context.create_context('options').execute()
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2/wscript", line 89, in options
    ctx.load('compiler_c')
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Context.py", line 90, in load
    fun(self)
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Tools/compiler_c.py", line 36, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Context.py", line 321, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Node.py", line 361, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/opt/mxe/tmp-aubio-i686-w64-mingw32.static/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Node.py", line 361, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
make[1]: *** [Makefile:900: build-only-aubio_i686-w64-mingw32.static] Error 2
make[1]: Leaving directory '/opt/mxe'

real	0m3.793s
user	0m3.580s
sys	0m0.300s

Cheers.

Phill.

**Comment by dschwen** [comment]
Same deal on Ubuntu 22.04.2 LTS, `aubio_i686-w64-mingw32.static` log attached. Same `StopIteration` raised in line 361...
[aubio_i686-w64-mingw32.static.txt](https://github.com/mxe/mxe/files/11986658/aubio_i686-w64-mingw32.static.txt)

So this has been broken for about 2 years for a bunch of people on different systems?
