### ISSUE TITLE
Package python-setuptools fails to build

### ISSUE THREAD

**Issue by jakint0sh** [mxe/mxe#3176]
The package `python-setuptools` fails to build, and this appears to be because it depends on the python module `setuptools`, which does not appear to be built/installed before MXE attempts to build setuptools.

```
jack@Jack-PC:~/dev/mxe$ make python-setuptools
[build]       python-setuptools       x86_64-pc-linux-gnu

Failed to build package python-setuptools for target x86_64-pc-linux-gnu!
------------------------------------------------------------
    subprocess.check_call(cmd)
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'setup.py', 'egg_info']' returned non-zero exit status 1.
make[1]: *** [Makefile:903: build-only-python-setuptools_x86_64-pc-linux-gnu] Error 1
make[1]: Leaving directory '/home/jack/dev/mxe'
real	0m2.485s
user	0m2.317s
sys	0m0.188s
------------------------------------------------------------
[log]      /home/jack/dev/mxe/log/python-setuptools_x86_64-pc-linux-gnu

make: *** [Makefile:891: /home/jack/dev/mxe/usr/x86_64-pc-linux-gnu/installed/python-setuptools] Error 1
jack@Jack-PC:~/dev/mxe$ cat log/python-setuptools_x86_64-pc-linux-gnu 
make[1]: Entering directory '/home/jack/dev/mxe'
uname -a
Linux Jack-PC 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
git log --pretty=tformat:"%H - %s [%ar] [%d]" -1
855a79825b10a422566de7fa14bcbe54e12847a8 - Update packages.json & build-matrix.html [30 hours ago] [ (HEAD -> master, origin/master, origin/HEAD)]
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
autoconf --version 2>/dev/null | head -1
autoconf (GNU Autoconf) 2.71
automake --version 2>/dev/null | head -1
automake (GNU automake) 1.16.5
gcc --version
gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ --version
g++ (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

python --version
Python 3.12.3
perl --version 2>&1 | head -3

This is perl 5, version 38, subversion 2 (v5.38.2) built for x86_64-linux-gnu-thread-multi
(with 44 registered patches, see perl -V for more detail)
rm -rf   '/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu'
mkdir -p '/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu'
mkdir -p '/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu/pypa-setuptools-df51e62'
mkdir -p '/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu/pypa-setuptools-df51e62.build_'
# disable wine with readonly directory
# see https://github.com/mxe/mxe/issues/841
mkdir -p '/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu/readonly'
chmod 0555 '/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu/readonly'
cd '/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu' &&   tar xzf '/home/jack/dev/mxe/pkg/python-setuptools-df51e62.tar.gz'
cd '/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu/pypa-setuptools-df51e62'
cd '/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu/pypa-setuptools-df51e62' && x86_64-pc-linux-gnu-python3.12 bootstrap.py
Traceback (most recent call last):
  File "/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu/pypa-setuptools-df51e62/setup.py", line 9, in <module>
    import setuptools
  File "/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu/pypa-setuptools-df51e62/setuptools/__init__.py", line 6, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'
adding minimal entry_points
Regenerating egg_info
Traceback (most recent call last):
  File "/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu/pypa-setuptools-df51e62/bootstrap.py", line 64, in <module>
    __name__ == '__main__' and main()
                               ^^^^^^
  File "/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu/pypa-setuptools-df51e62/bootstrap.py", line 61, in main
    run_egg_info()
  File "/home/jack/dev/mxe/tmp-python-setuptools-x86_64-pc-linux-gnu/pypa-setuptools-df51e62/bootstrap.py", line 54, in run_egg_info
    subprocess.check_call(cmd)
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'setup.py', 'egg_info']' returned non-zero exit status 1.
make[1]: *** [Makefile:903: build-only-python-setuptools_x86_64-pc-linux-gnu] Error 1
make[1]: Leaving directory '/home/jack/dev/mxe'

real	0m2.485s
user	0m2.317s
sys	0m0.188s
```

**Comment by mabrand** [comment]
Does it work for you now?

**Comment by jakint0sh** [comment]
Yep, works just fine now!
