### ISSUE TITLE
copydlldeps.py doesn't work for x86_64

### ISSUE THREAD

**Issue by alekseysidorov** [mxe/mxe#589]
Tested on Debian unstable

```bash
['/home/aleksey/develop/crossdev/mxe/tools/copydlldeps.py', '/home/aleksey/develop/cleverCNC/build/crossdev//install_root/mingw32_sniper_x86_64/CleverCNC/bin', '-C', '/home/aleksey/develop/cleverCNC/build/crossdev//install_root/mingw32_sniper_x86_64/CleverCNC/bin', '/home/aleksey/develop/cleverCNC/build/crossdev//install_root/mingw32_sniper_x86_64/CleverCNC/bin/imageformats', '-L', '/home/aleksey/develop/crossdev/mxe/usr/x86_64-w64-mingw32.shared/bin', '/home/aleksey/develop/crossdev/mxe/usr/x86_64-w64-mingw32.shared/lib', '/home/aleksey/develop/crossdev/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin']
Traceback (most recent call last):
  File "/home/aleksey/develop/crossdev/mxe/tools/copydlldeps.py", line 155, in <module>
    for dependency_dll in get_imports(pe_filename_full):
  File "/home/aleksey/develop/crossdev/mxe/tools/copydlldeps.py", line 73, in get_imports
    seek_to_rva(rva_of_import_table)
  File "/home/aleksey/develop/crossdev/mxe/tools/copydlldeps.py", line 69, in seek_to_rva
    raise ValueError('Could not find section for RVA.')
ValueError: Could not find section for RVA.

```

**Comment by tonytheodore** [comment]
Should be fixed in https://github.com/mxe/mxe/compare/6f830ee...4d76a91
